import type { Project } from "@/types";

const SECTION_LABELS: Record<string, string> = {
  Overview: "What it is",
  "Key Features": "What it does",
  "Design System": "How it looks",
  Compliance: "Compliance & access",
};

function sectionLabel(heading: string): string {
  return SECTION_LABELS[heading] ?? heading;
}

function buildMarkdown(project: Project): string {
  const date = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const latestVersion =
    project.versionHistory.length > 0
      ? project.versionHistory[0].version
      : "1.0";

  const lines: string[] = [
    `# ${project.name} \u2014 App Specification`,
    "",
    `*Generated by Caffeine \u00b7 ${date}*`,
    "",
    "---",
    "",
  ];

  if (project.specSections.length === 0) {
    lines.push(
      "*No specification content yet. Complete the Design flow to generate your spec.*",
    );
  } else {
    for (const section of project.specSections) {
      lines.push(`## ${sectionLabel(section.heading)}`);
      lines.push("");
      lines.push(section.content);
      lines.push("");
    }
  }

  lines.push("---");
  lines.push(
    `*Specification version ${latestVersion} \u00b7 Caffeine App Designer*`,
  );

  return lines.join("\n");
}

export function exportSpecAsMarkdown(project: Project): void {
  const md = buildMarkdown(project);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${project.name.replace(/\s+/g, "-").toLowerCase()}-spec.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function copySpecToClipboard(project: Project): Promise<void> {
  const md = buildMarkdown(project);
  await navigator.clipboard.writeText(md);
}
