import type { LiveApp, LogEntry, UserEntry, VersionEntry } from "./types";

export const LIVE_APPS: LiveApp[] = [
  {
    id: "community-hub",
    name: "Community Hub",
    status: "live",
    health: "ok",
    healthLabel: "All good",
    users: 1243,
    burnRateDisplay: "120K credits/day",
    burnRateNum: 120000,
    burnHistory: [100, 108, 112, 115, 118, 120, 120],
    lastDeploy: "2 days ago",
    version: "v4.2.1",
    description: "Community platform for local neighborhoods",
    runway: "~45 days left",
    runwayDays: 45,
  },
  {
    id: "clearpath-practice",
    name: "ClearPath Practice",
    status: "live",
    health: "warn",
    healthLabel: "Needs attention",
    users: 89,
    burnRateDisplay: "240K credits/day",
    burnRateNum: 240000,
    burnHistory: [160, 175, 190, 205, 220, 235, 240],
    lastDeploy: "1 day ago",
    version: "v2.0.3",
    description: "Medical practice management suite",
    runway: "~18 days left",
    runwayDays: 18,
  },
  {
    id: "vaultex-records",
    name: "VaultEx Records",
    status: "live",
    health: "ok",
    healthLabel: "All good",
    users: 312,
    burnRateDisplay: "95K credits/day",
    burnRateNum: 95000,
    burnHistory: [88, 90, 92, 95, 93, 96, 95],
    lastDeploy: "3 days ago",
    version: "v2.1.0",
    description: "Music rights management platform",
    runway: "~52 days left",
    runwayDays: 52,
  },
  {
    id: "taskflow-pro",
    name: "TaskFlow Pro",
    status: "live",
    health: "ok",
    healthLabel: "All good",
    users: 891,
    burnRateDisplay: "45K credits/day",
    burnRateNum: 45000,
    burnHistory: [40, 42, 44, 43, 45, 44, 45],
    lastDeploy: "1 week ago",
    version: "v3.4.2",
    description: "Team task management",
    runway: "~110 days left",
    runwayDays: 110,
  },
  {
    id: "meridian-analytics",
    name: "Meridian Analytics",
    status: "live",
    health: "warn",
    healthLabel: "Needs attention",
    users: 156,
    burnRateDisplay: "380K credits/day",
    burnRateNum: 380000,
    burnHistory: [200, 240, 280, 310, 340, 370, 380],
    lastDeploy: "5 days ago",
    version: "v1.0.8",
    description: "Business analytics dashboard",
    runway: "~12 days left",
    runwayDays: 12,
  },
  {
    id: "nexus-chat",
    name: "Nexus Chat",
    status: "live",
    health: "critical",
    healthLabel: "Needs attention",
    users: 78,
    burnRateDisplay: "520K credits/day",
    burnRateNum: 520000,
    burnHistory: [100, 200, 320, 400, 460, 500, 520],
    lastDeploy: "12 days ago",
    version: "v0.9.1",
    description: "Real-time messaging app",
    runway: "~4 days left",
    runwayDays: 4,
  },
];

export const INITIAL_USERS: Record<string, UserEntry[]> = {
  "community-hub": [
    {
      id: "u1",
      name: "Alice Chen",
      email: "alice@example.com",
      role: "Admin",
      joinedAt: "Jan 2025",
    },
    {
      id: "u2",
      name: "Bob Martinez",
      email: "bob@example.com",
      role: "Editor",
      joinedAt: "Feb 2025",
    },
    {
      id: "u3",
      name: "Carol Smith",
      email: "carol@example.com",
      role: "Viewer",
      joinedAt: "Mar 2025",
    },
  ],
  "clearpath-practice": [
    {
      id: "u4",
      name: "Dr. James Lee",
      email: "james@clearpath.io",
      role: "Admin",
      joinedAt: "Nov 2024",
    },
    {
      id: "u5",
      name: "Nurse Maya",
      email: "maya@clearpath.io",
      role: "Editor",
      joinedAt: "Dec 2024",
    },
  ],
  "vaultex-records": [
    {
      id: "u6",
      name: "Sam Rivera",
      email: "sam@vaultex.io",
      role: "Admin",
      joinedAt: "Jan 2025",
    },
  ],
  "taskflow-pro": [
    {
      id: "u7",
      name: "Emma Wilson",
      email: "emma@taskflow.io",
      role: "Admin",
      joinedAt: "Oct 2024",
    },
    {
      id: "u8",
      name: "Liam Brown",
      email: "liam@taskflow.io",
      role: "Editor",
      joinedAt: "Nov 2024",
    },
  ],
  "meridian-analytics": [
    {
      id: "u9",
      name: "Priya Patel",
      email: "priya@meridian.io",
      role: "Admin",
      joinedAt: "Mar 2025",
    },
  ],
  "nexus-chat": [
    {
      id: "u10",
      name: "Kai Nakamura",
      email: "kai@nexuschat.io",
      role: "Admin",
      joinedAt: "May 2025",
    },
  ],
};

export const INITIAL_ACCESS_LOGS: Record<string, LogEntry[]> = {
  "community-hub": [
    {
      id: "l1",
      timestamp: "2026-06-07 14:22",
      user: "alice@example.com",
      action: "Updated settings",
      ip: "192.168.1.1",
    },
    {
      id: "l2",
      timestamp: "2026-06-07 12:10",
      user: "bob@example.com",
      action: "Published post",
      ip: "10.0.0.5",
    },
  ],
  "clearpath-practice": [
    {
      id: "l3",
      timestamp: "2026-06-07 09:00",
      user: "james@clearpath.io",
      action: "Deployed v2.0.3",
      ip: "172.16.0.1",
    },
  ],
  "vaultex-records": [],
  "taskflow-pro": [
    {
      id: "l4",
      timestamp: "2026-06-06 16:45",
      user: "emma@taskflow.io",
      action: "Invited user",
      ip: "192.168.2.10",
    },
  ],
  "meridian-analytics": [],
  "nexus-chat": [],
};

export const INITIAL_DEPLOY_HISTORY: Record<string, VersionEntry[]> = {
  "community-hub": [
    {
      id: "v1",
      version: "v4.2.1",
      deployedAt: "2026-06-05",
      deployedBy: "alice@example.com",
      notes: "Bug fixes and performance",
      active: true,
    },
    {
      id: "v2",
      version: "v4.2.0",
      deployedAt: "2026-05-28",
      deployedBy: "alice@example.com",
      notes: "New notification system",
      active: false,
    },
  ],
  "clearpath-practice": [
    {
      id: "v3",
      version: "v2.0.3",
      deployedAt: "2026-06-06",
      deployedBy: "james@clearpath.io",
      notes: "Hotfix for scheduling bug",
      active: true,
    },
  ],
  "vaultex-records": [
    {
      id: "v4",
      version: "v2.1.0",
      deployedAt: "2026-06-04",
      deployedBy: "sam@vaultex.io",
      notes: "Rights dashboard improvements",
      active: true,
    },
  ],
  "taskflow-pro": [
    {
      id: "v5",
      version: "v3.4.2",
      deployedAt: "2026-05-31",
      deployedBy: "emma@taskflow.io",
      notes: "Mobile layout fixes",
      active: true,
    },
  ],
  "meridian-analytics": [
    {
      id: "v6",
      version: "v1.0.8",
      deployedAt: "2026-06-02",
      deployedBy: "priya@meridian.io",
      notes: "Chart performance fix",
      active: true,
    },
  ],
  "nexus-chat": [
    {
      id: "v7",
      version: "v0.9.1",
      deployedAt: "2026-05-26",
      deployedBy: "kai@nexuschat.io",
      notes: "Message threading",
      active: true,
    },
  ],
};

export const ROLES = ["Admin", "Editor", "Viewer"];
