/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AppCategory = IDL.Variant({
  'dashboard' : IDL.Null,
  'marketplace' : IDL.Null,
  'clubManager' : IDL.Null,
  'social' : IDL.Null,
  'other' : IDL.Null,
  'internalTool' : IDL.Null,
  'contentCms' : IDL.Null,
  'booking' : IDL.Null,
  'tracker' : IDL.Null,
});
export const ProjectId = IDL.Text;
export const Maturity = IDL.Variant({
  'idea' : IDL.Null,
  'defining' : IDL.Null,
  'live' : IDL.Null,
  'building' : IDL.Null,
  'exploring' : IDL.Null,
});
export const BuilderMode = IDL.Variant({
  'feel' : IDL.Null,
  'guided' : IDL.Null,
  'standard' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const ProjectMetadata = IDL.Record({
  'maturity' : Maturity,
  'tags' : IDL.Vec(IDL.Text),
  'builderMode' : BuilderMode,
  'priority' : IDL.Opt(Priority),
  'attentionFlag' : IDL.Bool,
});
export const Timestamp = IDL.Int;
export const DeploymentStatus = IDL.Variant({
  'notDeployed' : IDL.Null,
  'live' : IDL.Null,
  'failed' : IDL.Null,
});
export const ProjectVersion = IDL.Record({
  'specSnapshot' : IDL.Text,
  'version' : IDL.Text,
  'timestamp' : Timestamp,
  'changeSummary' : IDL.Text,
});
export const SpecSection = IDL.Record({
  'content' : IDL.Text,
  'heading' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : ProjectId,
  'metadata' : ProjectMetadata,
  'answers' : IDL.Text,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'deploymentStatus' : DeploymentStatus,
  'updatedAt' : Timestamp,
  'iconColor' : IDL.Text,
  'versionHistory' : IDL.Vec(ProjectVersion),
  'category' : AppCategory,
  'specSections' : IDL.Vec(SpecSection),
});
export const OrganizeFilters = IDL.Record({
  'maturity' : IDL.Opt(
    IDL.Variant({
      'idea' : IDL.Null,
      'defining' : IDL.Null,
      'live' : IDL.Null,
      'building' : IDL.Null,
      'exploring' : IDL.Null,
    })
  ),
  'tags' : IDL.Vec(IDL.Text),
  'deploymentStatus' : IDL.Opt(
    IDL.Variant({
      'notDeployed' : IDL.Null,
      'live' : IDL.Null,
      'failed' : IDL.Null,
    })
  ),
  'priority' : IDL.Opt(
    IDL.Variant({ 'low' : IDL.Null, 'high' : IDL.Null, 'medium' : IDL.Null })
  ),
});
export const SortBy = IDL.Variant({
  'name' : IDL.Null,
  'createdAt' : IDL.Null,
  'updatedAt' : IDL.Null,
  'priority' : IDL.Null,
});
export const UIState = IDL.Record({
  'organizeFilters' : OrganizeFilters,
  'sidebarCollapsed' : IDL.Bool,
  'activeProjectId' : IDL.Opt(IDL.Text),
  'activeMode' : IDL.Text,
  'organizeSortBy' : SortBy,
});
export const MetadataUpdate = IDL.Record({
  'maturity' : Maturity,
  'tags' : IDL.Vec(IDL.Text),
  'builderMode' : BuilderMode,
  'priority' : IDL.Opt(Priority),
  'attentionFlag' : IDL.Bool,
});

export const idlService = IDL.Service({
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, AppCategory],
      [Project],
      [],
    ),
  'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
  'duplicateProject' : IDL.Func([ProjectId, IDL.Text], [IDL.Opt(Project)], []),
  'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
  'getUIState' : IDL.Func([], [IDL.Opt(UIState)], ['query']),
  'isOnboardingComplete' : IDL.Func([], [IDL.Bool], ['query']),
  'isSampleProject' : IDL.Func([ProjectId], [IDL.Bool], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'markOnboardingComplete' : IDL.Func([], [], []),
  'saveUIState' : IDL.Func([UIState], [], []),
  'seedSampleProjects' : IDL.Func([], [IDL.Vec(Project)], []),
  'updateProjectAnswers' : IDL.Func(
      [ProjectId, IDL.Text],
      [IDL.Opt(Project)],
      [],
    ),
  'updateProjectMetadata' : IDL.Func(
      [ProjectId, MetadataUpdate],
      [IDL.Opt(Project)],
      [],
    ),
  'updateProjectSpec' : IDL.Func(
      [ProjectId, IDL.Vec(SpecSection)],
      [IDL.Opt(Project)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AppCategory = IDL.Variant({
    'dashboard' : IDL.Null,
    'marketplace' : IDL.Null,
    'clubManager' : IDL.Null,
    'social' : IDL.Null,
    'other' : IDL.Null,
    'internalTool' : IDL.Null,
    'contentCms' : IDL.Null,
    'booking' : IDL.Null,
    'tracker' : IDL.Null,
  });
  const ProjectId = IDL.Text;
  const Maturity = IDL.Variant({
    'idea' : IDL.Null,
    'defining' : IDL.Null,
    'live' : IDL.Null,
    'building' : IDL.Null,
    'exploring' : IDL.Null,
  });
  const BuilderMode = IDL.Variant({
    'feel' : IDL.Null,
    'guided' : IDL.Null,
    'standard' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ProjectMetadata = IDL.Record({
    'maturity' : Maturity,
    'tags' : IDL.Vec(IDL.Text),
    'builderMode' : BuilderMode,
    'priority' : IDL.Opt(Priority),
    'attentionFlag' : IDL.Bool,
  });
  const Timestamp = IDL.Int;
  const DeploymentStatus = IDL.Variant({
    'notDeployed' : IDL.Null,
    'live' : IDL.Null,
    'failed' : IDL.Null,
  });
  const ProjectVersion = IDL.Record({
    'specSnapshot' : IDL.Text,
    'version' : IDL.Text,
    'timestamp' : Timestamp,
    'changeSummary' : IDL.Text,
  });
  const SpecSection = IDL.Record({
    'content' : IDL.Text,
    'heading' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : ProjectId,
    'metadata' : ProjectMetadata,
    'answers' : IDL.Text,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'deploymentStatus' : DeploymentStatus,
    'updatedAt' : Timestamp,
    'iconColor' : IDL.Text,
    'versionHistory' : IDL.Vec(ProjectVersion),
    'category' : AppCategory,
    'specSections' : IDL.Vec(SpecSection),
  });
  const OrganizeFilters = IDL.Record({
    'maturity' : IDL.Opt(
      IDL.Variant({
        'idea' : IDL.Null,
        'defining' : IDL.Null,
        'live' : IDL.Null,
        'building' : IDL.Null,
        'exploring' : IDL.Null,
      })
    ),
    'tags' : IDL.Vec(IDL.Text),
    'deploymentStatus' : IDL.Opt(
      IDL.Variant({
        'notDeployed' : IDL.Null,
        'live' : IDL.Null,
        'failed' : IDL.Null,
      })
    ),
    'priority' : IDL.Opt(
      IDL.Variant({ 'low' : IDL.Null, 'high' : IDL.Null, 'medium' : IDL.Null })
    ),
  });
  const SortBy = IDL.Variant({
    'name' : IDL.Null,
    'createdAt' : IDL.Null,
    'updatedAt' : IDL.Null,
    'priority' : IDL.Null,
  });
  const UIState = IDL.Record({
    'organizeFilters' : OrganizeFilters,
    'sidebarCollapsed' : IDL.Bool,
    'activeProjectId' : IDL.Opt(IDL.Text),
    'activeMode' : IDL.Text,
    'organizeSortBy' : SortBy,
  });
  const MetadataUpdate = IDL.Record({
    'maturity' : Maturity,
    'tags' : IDL.Vec(IDL.Text),
    'builderMode' : BuilderMode,
    'priority' : IDL.Opt(Priority),
    'attentionFlag' : IDL.Bool,
  });
  
  return IDL.Service({
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, AppCategory],
        [Project],
        [],
      ),
    'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
    'duplicateProject' : IDL.Func(
        [ProjectId, IDL.Text],
        [IDL.Opt(Project)],
        [],
      ),
    'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
    'getUIState' : IDL.Func([], [IDL.Opt(UIState)], ['query']),
    'isOnboardingComplete' : IDL.Func([], [IDL.Bool], ['query']),
    'isSampleProject' : IDL.Func([ProjectId], [IDL.Bool], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'markOnboardingComplete' : IDL.Func([], [], []),
    'saveUIState' : IDL.Func([UIState], [], []),
    'seedSampleProjects' : IDL.Func([], [IDL.Vec(Project)], []),
    'updateProjectAnswers' : IDL.Func(
        [ProjectId, IDL.Text],
        [IDL.Opt(Project)],
        [],
      ),
    'updateProjectMetadata' : IDL.Func(
        [ProjectId, MetadataUpdate],
        [IDL.Opt(Project)],
        [],
      ),
    'updateProjectSpec' : IDL.Func(
        [ProjectId, IDL.Vec(SpecSection)],
        [IDL.Opt(Project)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };