/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppCategory = { 'dashboard' : null } |
  { 'marketplace' : null } |
  { 'clubManager' : null } |
  { 'social' : null } |
  { 'other' : null } |
  { 'internalTool' : null } |
  { 'contentCms' : null } |
  { 'booking' : null } |
  { 'tracker' : null };
export type BuilderMode = { 'feel' : null } |
  { 'guided' : null } |
  { 'standard' : null };
export type DeploymentStatus = { 'notDeployed' : null } |
  { 'live' : null } |
  { 'failed' : null };
export type Maturity = { 'idea' : null } |
  { 'defining' : null } |
  { 'live' : null } |
  { 'building' : null } |
  { 'exploring' : null };
export interface MetadataUpdate {
  'maturity' : Maturity,
  'tags' : Array<string>,
  'builderMode' : BuilderMode,
  'priority' : [] | [Priority],
  'attentionFlag' : boolean,
}
export interface OrganizeFilters {
  'maturity' : [] | [
    { 'idea' : null } |
      { 'defining' : null } |
      { 'live' : null } |
      { 'building' : null } |
      { 'exploring' : null }
  ],
  'tags' : Array<string>,
  'deploymentStatus' : [] | [
    { 'notDeployed' : null } |
      { 'live' : null } |
      { 'failed' : null }
  ],
  'priority' : [] | [
    { 'low' : null } |
      { 'high' : null } |
      { 'medium' : null }
  ],
}
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Project {
  'id' : ProjectId,
  'metadata' : ProjectMetadata,
  'answers' : string,
  'icon' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'deploymentStatus' : DeploymentStatus,
  'updatedAt' : Timestamp,
  'iconColor' : string,
  'versionHistory' : Array<ProjectVersion>,
  'category' : AppCategory,
  'specSections' : Array<SpecSection>,
}
export type ProjectId = string;
export interface ProjectMetadata {
  'maturity' : Maturity,
  'tags' : Array<string>,
  'builderMode' : BuilderMode,
  'priority' : [] | [Priority],
  'attentionFlag' : boolean,
}
export interface ProjectVersion {
  'specSnapshot' : string,
  'version' : string,
  'timestamp' : Timestamp,
  'changeSummary' : string,
}
export type SortBy = { 'name' : null } |
  { 'createdAt' : null } |
  { 'updatedAt' : null } |
  { 'priority' : null };
export interface SpecSection { 'content' : string, 'heading' : string }
export type Timestamp = bigint;
export interface UIState {
  'organizeFilters' : OrganizeFilters,
  'sidebarCollapsed' : boolean,
  'activeProjectId' : [] | [string],
  'activeMode' : string,
  'organizeSortBy' : SortBy,
}
export interface _SERVICE {
  'createProject' : ActorMethod<[string, string, string, AppCategory], Project>,
  'deleteProject' : ActorMethod<[ProjectId], boolean>,
  'duplicateProject' : ActorMethod<[ProjectId, string], [] | [Project]>,
  'getProject' : ActorMethod<[ProjectId], [] | [Project]>,
  'getUIState' : ActorMethod<[], [] | [UIState]>,
  'isOnboardingComplete' : ActorMethod<[], boolean>,
  'isSampleProject' : ActorMethod<[ProjectId], boolean>,
  'listProjects' : ActorMethod<[], Array<Project>>,
  'markOnboardingComplete' : ActorMethod<[], undefined>,
  'saveUIState' : ActorMethod<[UIState], undefined>,
  'seedSampleProjects' : ActorMethod<[], Array<Project>>,
  'updateProjectAnswers' : ActorMethod<[ProjectId, string], [] | [Project]>,
  'updateProjectMetadata' : ActorMethod<
    [ProjectId, MetadataUpdate],
    [] | [Project]
  >,
  'updateProjectSpec' : ActorMethod<
    [ProjectId, Array<SpecSection>],
    [] | [Project]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];