/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface OrganizeFilters {
    maturity?: Variant_idea_defining_live_building_exploring;
    tags: Array<string>;
    deploymentStatus?: Variant_notDeployed_live_failed;
    priority?: Variant_low_high_medium;
}
export type Timestamp = bigint;
export interface ProjectVersion {
    specSnapshot: string;
    version: string;
    timestamp: Timestamp;
    changeSummary: string;
}
export interface ProjectMetadata {
    maturity: Maturity;
    tags: Array<string>;
    builderMode: BuilderMode;
    priority?: Priority;
    attentionFlag: boolean;
}
export interface MetadataUpdate {
    maturity: Maturity;
    tags: Array<string>;
    builderMode: BuilderMode;
    priority?: Priority;
    attentionFlag: boolean;
}
export interface SpecSection {
    content: string;
    heading: string;
}
export type ProjectId = string;
export interface UIState {
    organizeFilters: OrganizeFilters;
    sidebarCollapsed: boolean;
    activeProjectId?: string;
    activeMode: string;
    organizeSortBy: SortBy;
}
export interface Project {
    id: ProjectId;
    metadata: ProjectMetadata;
    answers: string;
    icon: string;
    name: string;
    createdAt: Timestamp;
    deploymentStatus: DeploymentStatus;
    updatedAt: Timestamp;
    iconColor: string;
    versionHistory: Array<ProjectVersion>;
    category: AppCategory;
    specSections: Array<SpecSection>;
}
export enum AppCategory {
    dashboard = "dashboard",
    marketplace = "marketplace",
    clubManager = "clubManager",
    social = "social",
    other = "other",
    internalTool = "internalTool",
    contentCms = "contentCms",
    booking = "booking",
    tracker = "tracker"
}
export enum BuilderMode {
    feel = "feel",
    guided = "guided",
    standard = "standard"
}
export enum SortBy {
    name = "name",
    createdAt = "createdAt",
    updatedAt = "updatedAt",
    priority = "priority"
}
export enum Variant_idea_defining_live_building_exploring {
    idea = "idea",
    defining = "defining",
    live = "live",
    building = "building",
    exploring = "exploring"
}
export enum Variant_low_high_medium {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Variant_notDeployed_live_failed {
    notDeployed = "notDeployed",
    live = "live",
    failed = "failed"
}
export interface backendInterface {
    createProject(name: string, icon: string, iconColor: string, category: AppCategory): Promise<Project>;
    deleteProject(id: ProjectId): Promise<boolean>;
    duplicateProject(id: ProjectId, newName: string): Promise<Project | null>;
    getProject(id: ProjectId): Promise<Project | null>;
    getUIState(): Promise<UIState | null>;
    isOnboardingComplete(): Promise<boolean>;
    isSampleProject(id: ProjectId): Promise<boolean>;
    listProjects(): Promise<Array<Project>>;
    markOnboardingComplete(): Promise<void>;
    saveUIState(state: UIState): Promise<void>;
    seedSampleProjects(): Promise<Array<Project>>;
    updateProjectAnswers(id: ProjectId, answers: string): Promise<Project | null>;
    updateProjectMetadata(id: ProjectId, metadata: MetadataUpdate): Promise<Project | null>;
    updateProjectSpec(id: ProjectId, sections: Array<SpecSection>): Promise<Project | null>;
}
import type { AppCategory as _AppCategory, BuilderMode as _BuilderMode, DeploymentStatus as _DeploymentStatus, Maturity as _Maturity, MetadataUpdate as _MetadataUpdate, OrganizeFilters as _OrganizeFilters, Priority as _Priority, Project as _Project, ProjectId as _ProjectId, ProjectMetadata as _ProjectMetadata, ProjectVersion as _ProjectVersion, SortBy as _SortBy, SpecSection as _SpecSection, Timestamp as _Timestamp, UIState as _UIState } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createProject(arg0: string, arg1: string, arg2: string, arg3: AppCategory): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1, arg2, to_candid_AppCategory_n1(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Project_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1, arg2, to_candid_AppCategory_n1(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Project_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProject(arg0: ProjectId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async duplicateProject(arg0: ProjectId, arg1: string): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicateProject(arg0, arg1);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicateProject(arg0, arg1);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: ProjectId): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUIState(): Promise<UIState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUIState();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUIState();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isOnboardingComplete(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOnboardingComplete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOnboardingComplete();
            return result;
        }
    }
    async isSampleProject(arg0: ProjectId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSampleProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSampleProject(arg0);
            return result;
        }
    }
    async listProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async markOnboardingComplete(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markOnboardingComplete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markOnboardingComplete();
            return result;
        }
    }
    async saveUIState(arg0: UIState): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUIState(to_candid_UIState_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUIState(to_candid_UIState_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async seedSampleProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleProjects();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleProjects();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProjectAnswers(arg0: ProjectId, arg1: string): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectAnswers(arg0, arg1);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectAnswers(arg0, arg1);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProjectMetadata(arg0: ProjectId, arg1: MetadataUpdate): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectMetadata(arg0, to_candid_MetadataUpdate_n40(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectMetadata(arg0, to_candid_MetadataUpdate_n40(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProjectSpec(arg0: ProjectId, arg1: Array<SpecSection>): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectSpec(arg0, arg1);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectSpec(arg0, arg1);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppCategory): AppCategory {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_BuilderMode_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BuilderMode): BuilderMode {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_DeploymentStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeploymentStatus): DeploymentStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Maturity_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Maturity): Maturity {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_OrganizeFilters_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrganizeFilters): OrganizeFilters {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectMetadata_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectMetadata): ProjectMetadata {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_SortBy_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SortBy): SortBy {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UIState_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UIState): UIState {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Priority]): Priority | null {
    return value.length === 0 ? null : from_candid_Priority_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UIState]): UIState | null {
    return value.length === 0 ? null : from_candid_UIState_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        idea: null;
    } | {
        defining: null;
    } | {
        live: null;
    } | {
        building: null;
    } | {
        exploring: null;
    }]): Variant_idea_defining_live_building_exploring | null {
    return value.length === 0 ? null : from_candid_variant_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        notDeployed: null;
    } | {
        live: null;
    } | {
        failed: null;
    }]): Variant_notDeployed_live_failed | null {
    return value.length === 0 ? null : from_candid_variant_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        low: null;
    } | {
        high: null;
    } | {
        medium: null;
    }]): Variant_low_high_medium | null {
    return value.length === 0 ? null : from_candid_variant_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organizeFilters: _OrganizeFilters;
    sidebarCollapsed: boolean;
    activeProjectId: [] | [string];
    activeMode: string;
    organizeSortBy: _SortBy;
}): {
    organizeFilters: OrganizeFilters;
    sidebarCollapsed: boolean;
    activeProjectId?: string;
    activeMode: string;
    organizeSortBy: SortBy;
} {
    return {
        organizeFilters: from_candid_OrganizeFilters_n22(_uploadFile, _downloadFile, value.organizeFilters),
        sidebarCollapsed: value.sidebarCollapsed,
        activeProjectId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.activeProjectId)),
        activeMode: value.activeMode,
        organizeSortBy: from_candid_SortBy_n28(_uploadFile, _downloadFile, value.organizeSortBy)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maturity: [] | [{
            idea: null;
        } | {
            defining: null;
        } | {
            live: null;
        } | {
            building: null;
        } | {
            exploring: null;
        }];
    tags: Array<string>;
    deploymentStatus: [] | [{
            notDeployed: null;
        } | {
            live: null;
        } | {
            failed: null;
        }];
    priority: [] | [{
            low: null;
        } | {
            high: null;
        } | {
            medium: null;
        }];
}): {
    maturity?: Variant_idea_defining_live_building_exploring;
    tags: Array<string>;
    deploymentStatus?: Variant_notDeployed_live_failed;
    priority?: Variant_low_high_medium;
} {
    return {
        maturity: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.maturity)),
        tags: value.tags,
        deploymentStatus: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.deploymentStatus)),
        priority: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.priority))
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProjectId;
    metadata: _ProjectMetadata;
    answers: string;
    icon: string;
    name: string;
    createdAt: _Timestamp;
    deploymentStatus: _DeploymentStatus;
    updatedAt: _Timestamp;
    iconColor: string;
    versionHistory: Array<_ProjectVersion>;
    category: _AppCategory;
    specSections: Array<_SpecSection>;
}): {
    id: ProjectId;
    metadata: ProjectMetadata;
    answers: string;
    icon: string;
    name: string;
    createdAt: Timestamp;
    deploymentStatus: DeploymentStatus;
    updatedAt: Timestamp;
    iconColor: string;
    versionHistory: Array<ProjectVersion>;
    category: AppCategory;
    specSections: Array<SpecSection>;
} {
    return {
        id: value.id,
        metadata: from_candid_ProjectMetadata_n5(_uploadFile, _downloadFile, value.metadata),
        answers: value.answers,
        icon: value.icon,
        name: value.name,
        createdAt: value.createdAt,
        deploymentStatus: from_candid_DeploymentStatus_n14(_uploadFile, _downloadFile, value.deploymentStatus),
        updatedAt: value.updatedAt,
        iconColor: value.iconColor,
        versionHistory: value.versionHistory,
        category: from_candid_AppCategory_n16(_uploadFile, _downloadFile, value.category),
        specSections: value.specSections
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maturity: _Maturity;
    tags: Array<string>;
    builderMode: _BuilderMode;
    priority: [] | [_Priority];
    attentionFlag: boolean;
}): {
    maturity: Maturity;
    tags: Array<string>;
    builderMode: BuilderMode;
    priority?: Priority;
    attentionFlag: boolean;
} {
    return {
        maturity: from_candid_Maturity_n7(_uploadFile, _downloadFile, value.maturity),
        tags: value.tags,
        builderMode: from_candid_BuilderMode_n9(_uploadFile, _downloadFile, value.builderMode),
        priority: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.priority)),
        attentionFlag: value.attentionFlag
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    feel: null;
} | {
    guided: null;
} | {
    standard: null;
}): BuilderMode {
    return "feel" in value ? BuilderMode.feel : "guided" in value ? BuilderMode.guided : "standard" in value ? BuilderMode.standard : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Variant_low_high_medium {
    return "low" in value ? Variant_low_high_medium.low : "high" in value ? Variant_low_high_medium.high : "medium" in value ? Variant_low_high_medium.medium : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notDeployed: null;
} | {
    live: null;
} | {
    failed: null;
}): Variant_notDeployed_live_failed {
    return "notDeployed" in value ? Variant_notDeployed_live_failed.notDeployed : "live" in value ? Variant_notDeployed_live_failed.live : "failed" in value ? Variant_notDeployed_live_failed.failed : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dashboard: null;
} | {
    marketplace: null;
} | {
    clubManager: null;
} | {
    social: null;
} | {
    other: null;
} | {
    internalTool: null;
} | {
    contentCms: null;
} | {
    booking: null;
} | {
    tracker: null;
}): AppCategory {
    return "dashboard" in value ? AppCategory.dashboard : "marketplace" in value ? AppCategory.marketplace : "clubManager" in value ? AppCategory.clubManager : "social" in value ? AppCategory.social : "other" in value ? AppCategory.other : "internalTool" in value ? AppCategory.internalTool : "contentCms" in value ? AppCategory.contentCms : "booking" in value ? AppCategory.booking : "tracker" in value ? AppCategory.tracker : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: null;
} | {
    createdAt: null;
} | {
    updatedAt: null;
} | {
    priority: null;
}): SortBy {
    return "name" in value ? SortBy.name : "createdAt" in value ? SortBy.createdAt : "updatedAt" in value ? SortBy.updatedAt : "priority" in value ? SortBy.priority : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    idea: null;
} | {
    defining: null;
} | {
    live: null;
} | {
    building: null;
} | {
    exploring: null;
}): Variant_idea_defining_live_building_exploring {
    return "idea" in value ? Variant_idea_defining_live_building_exploring.idea : "defining" in value ? Variant_idea_defining_live_building_exploring.defining : "live" in value ? Variant_idea_defining_live_building_exploring.live : "building" in value ? Variant_idea_defining_live_building_exploring.building : "exploring" in value ? Variant_idea_defining_live_building_exploring.exploring : value;
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n3(_uploadFile, _downloadFile, x));
}
function to_candid_AppCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppCategory): _AppCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_BuilderMode_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BuilderMode): _BuilderMode {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_Maturity_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Maturity): _Maturity {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_MetadataUpdate_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MetadataUpdate): _MetadataUpdate {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_OrganizeFilters_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrganizeFilters): _OrganizeFilters {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_SortBy_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortBy): _SortBy {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UIState_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UIState): _UIState {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organizeFilters: OrganizeFilters;
    sidebarCollapsed: boolean;
    activeProjectId?: string;
    activeMode: string;
    organizeSortBy: SortBy;
}): {
    organizeFilters: _OrganizeFilters;
    sidebarCollapsed: boolean;
    activeProjectId: [] | [string];
    activeMode: string;
    organizeSortBy: _SortBy;
} {
    return {
        organizeFilters: to_candid_OrganizeFilters_n33(_uploadFile, _downloadFile, value.organizeFilters),
        sidebarCollapsed: value.sidebarCollapsed,
        activeProjectId: value.activeProjectId ? candid_some(value.activeProjectId) : candid_none(),
        activeMode: value.activeMode,
        organizeSortBy: to_candid_SortBy_n38(_uploadFile, _downloadFile, value.organizeSortBy)
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maturity?: Variant_idea_defining_live_building_exploring;
    tags: Array<string>;
    deploymentStatus?: Variant_notDeployed_live_failed;
    priority?: Variant_low_high_medium;
}): {
    maturity: [] | [{
            idea: null;
        } | {
            defining: null;
        } | {
            live: null;
        } | {
            building: null;
        } | {
            exploring: null;
        }];
    tags: Array<string>;
    deploymentStatus: [] | [{
            notDeployed: null;
        } | {
            live: null;
        } | {
            failed: null;
        }];
    priority: [] | [{
            low: null;
        } | {
            high: null;
        } | {
            medium: null;
        }];
} {
    return {
        maturity: value.maturity ? candid_some(to_candid_variant_n35(_uploadFile, _downloadFile, value.maturity)) : candid_none(),
        tags: value.tags,
        deploymentStatus: value.deploymentStatus ? candid_some(to_candid_variant_n36(_uploadFile, _downloadFile, value.deploymentStatus)) : candid_none(),
        priority: value.priority ? candid_some(to_candid_variant_n37(_uploadFile, _downloadFile, value.priority)) : candid_none()
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maturity: Maturity;
    tags: Array<string>;
    builderMode: BuilderMode;
    priority?: Priority;
    attentionFlag: boolean;
}): {
    maturity: _Maturity;
    tags: Array<string>;
    builderMode: _BuilderMode;
    priority: [] | [_Priority];
    attentionFlag: boolean;
} {
    return {
        maturity: to_candid_Maturity_n42(_uploadFile, _downloadFile, value.maturity),
        tags: value.tags,
        builderMode: to_candid_BuilderMode_n43(_uploadFile, _downloadFile, value.builderMode),
        priority: value.priority ? candid_some(to_candid_Priority_n45(_uploadFile, _downloadFile, value.priority)) : candid_none(),
        attentionFlag: value.attentionFlag
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppCategory): {
    dashboard: null;
} | {
    marketplace: null;
} | {
    clubManager: null;
} | {
    social: null;
} | {
    other: null;
} | {
    internalTool: null;
} | {
    contentCms: null;
} | {
    booking: null;
} | {
    tracker: null;
} {
    return value == AppCategory.dashboard ? {
        dashboard: null
    } : value == AppCategory.marketplace ? {
        marketplace: null
    } : value == AppCategory.clubManager ? {
        clubManager: null
    } : value == AppCategory.social ? {
        social: null
    } : value == AppCategory.other ? {
        other: null
    } : value == AppCategory.internalTool ? {
        internalTool: null
    } : value == AppCategory.contentCms ? {
        contentCms: null
    } : value == AppCategory.booking ? {
        booking: null
    } : value == AppCategory.tracker ? {
        tracker: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_idea_defining_live_building_exploring): {
    idea: null;
} | {
    defining: null;
} | {
    live: null;
} | {
    building: null;
} | {
    exploring: null;
} {
    return value == Variant_idea_defining_live_building_exploring.idea ? {
        idea: null
    } : value == Variant_idea_defining_live_building_exploring.defining ? {
        defining: null
    } : value == Variant_idea_defining_live_building_exploring.live ? {
        live: null
    } : value == Variant_idea_defining_live_building_exploring.building ? {
        building: null
    } : value == Variant_idea_defining_live_building_exploring.exploring ? {
        exploring: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_notDeployed_live_failed): {
    notDeployed: null;
} | {
    live: null;
} | {
    failed: null;
} {
    return value == Variant_notDeployed_live_failed.notDeployed ? {
        notDeployed: null
    } : value == Variant_notDeployed_live_failed.live ? {
        live: null
    } : value == Variant_notDeployed_live_failed.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_low_high_medium): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Variant_low_high_medium.low ? {
        low: null
    } : value == Variant_low_high_medium.high ? {
        high: null
    } : value == Variant_low_high_medium.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortBy): {
    name: null;
} | {
    createdAt: null;
} | {
    updatedAt: null;
} | {
    priority: null;
} {
    return value == SortBy.name ? {
        name: null
    } : value == SortBy.createdAt ? {
        createdAt: null
    } : value == SortBy.updatedAt ? {
        updatedAt: null
    } : value == SortBy.priority ? {
        priority: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BuilderMode): {
    feel: null;
} | {
    guided: null;
} | {
    standard: null;
} {
    return value == BuilderMode.feel ? {
        feel: null
    } : value == BuilderMode.guided ? {
        guided: null
    } : value == BuilderMode.standard ? {
        standard: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
